In [3]:
import gymnasium as gym
import numpy as np

env = gym.make("FrozenLake-v1", is_slippery=True, render_mode="human")
env.reset()
env.render()

In [4]:
print("Nombre d'états :", env.observation_space.n)
print("Nombre d'actions :", env.action_space.n)


Nombre d'états : 16
Nombre d'actions : 4


In [5]:
num_episodes = 5

for episode in range(num_episodes):
    state, _ = env.reset()
    done = False
    print(f"\nÉpisode {episode + 1}\n{'-' * 20}")

    while not done:
        # Choisir une action aléatoire
        action = env.action_space.sample()

        # Appliquer l’action
        next_state, reward, done, truncated, info = env.step(action)

        print(f"Action: {action}, État suivant: {next_state}, Récompense: {reward}")

        # Si l'épisode est terminé, sortir de la boucle
        if done or truncated:
            print("Épisode terminé.\n")
            break

env.close()



Épisode 1
--------------------
Action: 0, État suivant: 4, Récompense: 0.0
Action: 2, État suivant: 5, Récompense: 0.0
Épisode terminé.


Épisode 2
--------------------
Action: 3, État suivant: 0, Récompense: 0.0
Action: 2, État suivant: 4, Récompense: 0.0
Action: 3, État suivant: 4, Récompense: 0.0
Action: 2, État suivant: 0, Récompense: 0.0
Action: 1, État suivant: 4, Récompense: 0.0
Action: 1, État suivant: 4, Récompense: 0.0
Action: 3, État suivant: 5, Récompense: 0.0
Épisode terminé.


Épisode 3
--------------------
Action: 2, État suivant: 1, Récompense: 0.0
Action: 1, État suivant: 0, Récompense: 0.0
Action: 2, État suivant: 1, Récompense: 0.0
Action: 2, État suivant: 5, Récompense: 0.0
Épisode terminé.


Épisode 4
--------------------
Action: 1, État suivant: 0, Récompense: 0.0
Action: 1, État suivant: 0, Récompense: 0.0
Action: 3, État suivant: 1, Récompense: 0.0
Action: 3, État suivant: 0, Récompense: 0.0
Action: 3, État suivant: 1, Récompense: 0.0
Action: 1, État suivant: 2

In [6]:
import gymnasium as gym

# Charger l’environnement FrozenLake
env = gym.make("FrozenLake-v1", is_slippery=True)

num_episodes = 10

for episode in range(num_episodes):
    state, _ = env.reset()
    done = False
    print(f"\nÉpisode {episode + 1}\n{'-' * 20}")

    while not done:
        # Choisir une action aléatoire
        action = env.action_space.sample()

        # Appliquer l’action
        next_state, reward, done, truncated, info = env.step(action)

        print(f"Action: {action}, État suivant: {next_state}, Récompense: {reward}")

        # Si l'épisode est terminé, sortir de la boucle
        if done or truncated:
            print("Épisode terminé.\n")
            break
 
env.close()



Épisode 1
--------------------
Action: 0, État suivant: 0, Récompense: 0.0
Action: 3, État suivant: 0, Récompense: 0.0
Action: 2, État suivant: 1, Récompense: 0.0
Action: 2, État suivant: 2, Récompense: 0.0
Action: 2, État suivant: 3, Récompense: 0.0
Action: 0, État suivant: 2, Récompense: 0.0
Action: 0, État suivant: 6, Récompense: 0.0
Action: 0, État suivant: 10, Récompense: 0.0
Action: 0, État suivant: 9, Récompense: 0.0
Action: 3, État suivant: 5, Récompense: 0.0
Épisode terminé.


Épisode 2
--------------------
Action: 0, État suivant: 0, Récompense: 0.0
Action: 2, État suivant: 0, Récompense: 0.0
Action: 1, État suivant: 4, Récompense: 0.0
Action: 1, État suivant: 8, Récompense: 0.0
Action: 3, État suivant: 9, Récompense: 0.0
Action: 0, État suivant: 5, Récompense: 0.0
Épisode terminé.


Épisode 3
--------------------
Action: 0, État suivant: 0, Récompense: 0.0
Action: 3, État suivant: 0, Récompense: 0.0
Action: 2, État suivant: 0, Récompense: 0.0
Action: 2, État suivant: 0, Réc

In [7]:
import numpy as np
import gymnasium as gym

# Charger l'environnement FrozenLake
env = gym.make("FrozenLake-v1", is_slippery=True)

# Obtenir le nombre d'états et d'actions
num_states = env.observation_space.n
num_actions = env.action_space.n

# Créer et initialiser la Q-Table à 0
q_table = np.zeros((num_states, num_actions))

print("Q-Table initialisée :")
print(q_table)


Q-Table initialisée :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# Paramètres
alpha = 0.1  # Taux d'apprentissage
gamma = 0.99  # Facteur de discount
epsilon = 1.0  # Exploration initiale
epsilon_decay = 0.995  # Décroissance d'epsilon
num_episodes = 5000  # Nombre d'épisodes

# Boucle d'apprentissage
for episode in range(num_episodes):
    state = env.reset()[0]  # État initial
    done = False

    while not done:
        if np.random.rand() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])


        new_state, reward, done, truncated, info = env.step(action)

        # Mettre à jour la Q-Table
        q_table[state, action] = q_table[state, action] + alpha * (
            reward + gamma * np.max(q_table[new_state]) - q_table[state, action]
        )

        # Mettre à jour l'état
        state = new_state

    # Réduire epsilon (moins d'exploration au fil du temps)
    epsilon = max(0.01, epsilon * epsilon_decay)

# Affichage de la Q-Table après l'apprentissage
print("Q-Table après apprentissage :")
print(q_table)


Q-Table après apprentissage :
[[0.10562349 0.10162517 0.10386433 0.10693768]
 [0.09812903 0.08644038 0.0697654  0.10524712]
 [0.10030592 0.09897262 0.09394128 0.10056544]
 [0.03435376 0.03357259 0.03678962 0.09940053]
 [0.10981433 0.04033252 0.05643914 0.04161711]
 [0.         0.         0.         0.        ]
 [0.13977526 0.04764047 0.06463965 0.05575012]
 [0.         0.         0.         0.        ]
 [0.02965009 0.06231894 0.11929298 0.05569826]
 [0.04663432 0.25762811 0.04603051 0.0666746 ]
 [0.29950322 0.20570754 0.09592647 0.11114244]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.02519346 0.         0.         0.21178676]
 [0.17729454 0.4105384  0.75826294 0.22648988]
 [0.         0.         0.         0.        ]]
